"""movies table

Revision ID: 6ff25c43f07f
Revises: 
Create Date: 2025-02-12 19:51:12.307414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff25c43f07f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_director'), ['director'], unique=True)
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.drop_index(batch_op.f('ix_movie_director'))

    op.drop_table('movie')
    # ### end Alembic commands ###
