"""better actor, movie and borrowing table and their relations

Revision ID: 837fc58ee937
Revises: 6ff25c43f07f
Create Date: 2025-02-12 21:11:24.332369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837fc58ee937'
down_revision = '6ff25c43f07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_name'), ['name'], unique=True)

    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowed', sa.Boolean(), nullable=True),
    sa.Column('date_borrowed', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowing_date_borrowed'), ['date_borrowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrowing_date_returned'), ['date_returned'], unique=False)

    op.create_table('movies_actors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_director')
        batch_op.drop_column('director')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_movie_director', ['director'], unique=1)

    op.drop_table('movies_actors')
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowing_date_returned'))
        batch_op.drop_index(batch_op.f('ix_borrowing_date_borrowed'))

    op.drop_table('borrowing')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_name'))

    op.drop_table('actor')
    # ### end Alembic commands ###
